<?php

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {

        $State = [
            ['StateName'=>'Andaman and Nicobar Island (UT)','created_at'=>now(),'updated_at'=>now()],
            ['StateName'=>'Andhra Pradesh','created_at'=>now(),'updated_at'=>now()],
            ['StateName'=>'Arunachal Pradesh','created_at'=>now(),'updated_at'=>now()],
            ['StateName'=>'Assam','created_at'=>now(),'updated_at'=>now()],
            ['StateName'=>'Bihar','created_at'=>now(),'updated_at'=>now()],
            ['StateName'=>'Chandigarh (UT)','created_at'=>now(),'updated_at'=>now()],
            ['StateName'=>'Chhattisgarh','created_at'=>now(),'updated_at'=>now()],
            ['StateName'=>'Dadra and Nagar Haveli (UT)','created_at'=>now(),'updated_at'=>now()],
            ['StateName'=>'Daman and Diu (UT)','created_at'=>now(),'updated_at'=>now()],
            ['StateName'=>'Delhi (NCT)','created_at'=>now(),'updated_at'=>now()],
            ['StateName'=>'Goa','created_at'=>now(),'updated_at'=>now()],
            ['StateName'=>'Gujarat','created_at'=>now(),'updated_at'=>now()],
            ['StateName'=>'Haryana','created_at'=>now(),'updated_at'=>now()],
            ['StateName'=>'Himachal Pradesh','created_at'=>now(),'updated_at'=>now()],
            ['StateName'=>'Jammu and Kashmir','created_at'=>now(),'updated_at'=>now()],
            ['StateName'=>'Jharkhand','created_at'=>now(),'updated_at'=>now()],
            ['StateName'=>'Karnataka','created_at'=>now(),'updated_at'=>now()],
            ['StateName'=>'Kerala','created_at'=>now(),'updated_at'=>now()],
            ['StateName'=>'Lakshadweep (UT)','created_at'=>now(),'updated_at'=>now()],
            ['StateName'=>'Madhya Pradesh','created_at'=>now(),'updated_at'=>now()],
            ['StateName'=>'Maharashtra','created_at'=>now(),'updated_at'=>now()],
            ['StateName'=>'Manipur','created_at'=>now(),'updated_at'=>now()],
            ['StateName'=>'Meghalaya','created_at'=>now(),'updated_at'=>now()],
            ['StateName'=>'Mizoram','created_at'=>now(),'updated_at'=>now()],
            ['StateName'=>'Nagaland','created_at'=>now(),'updated_at'=>now()],
            ['StateName'=>'Odisha','created_at'=>now(),'updated_at'=>now()],
            ['StateName'=>'Puducherry (UT)','created_at'=>now(),'updated_at'=>now()],
            ['StateName'=>'Punjab','created_at'=>now(),'updated_at'=>now()],
            ['StateName'=>'Rajastha','created_at'=>now(),'updated_at'=>now()],
            ['StateName'=>'Sikkim','created_at'=>now(),'updated_at'=>now()],
            ['StateName'=>'Tamil Nadu','created_at'=>now(),'updated_at'=>now()],
            ['StateName'=>'Telangana','created_at'=>now(),'updated_at'=>now()],
            ['StateName'=>'Tripura','created_at'=>now(),'updated_at'=>now()],
            ['StateName'=>'Uttarakhand','created_at'=>now(),'updated_at'=>now()],
            ['StateName'=>'Uttar Pradesh','created_at'=>now(),'updated_at'=>now()],
            ['StateName'=>'West Bengal','created_at'=>now(),'updated_at'=>now()],
        ];

        DB::table('states')->insert($State);

        $District = [
            ['state_id'=>1,'DistrictName'=>'North and Middle Andama','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>1,'DistrictName'=>'South Andama','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>1,'DistrictName'=>'Nicobar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>2,'DistrictName'=>'Anantapur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>2,'DistrictName'=>'Chittoor','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>2,'DistrictName'=>'East Godavari','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>2,'DistrictName'=>'Guntur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>2,'DistrictName'=>'Krishna','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>2,'DistrictName'=>'Kurnool','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>2,'DistrictName'=>'Prakasam','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>2,'DistrictName'=>'Srikakulam','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>2,'DistrictName'=>'Sri Potti Sri Ramulu Nellore','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>2,'DistrictName'=>'Vishakhapatnam','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>2,'DistrictName'=>'Vizianagaram','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>2,'DistrictName'=>'West Godavari','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>2,'DistrictName'=>'Cudappah','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>3,'DistrictName'=>'Anjaw','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>3,'DistrictName'=>'Changlang','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>3,'DistrictName'=>'East Siang','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>3,'DistrictName'=>'East Kameng','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>3,'DistrictName'=>'Kurung Kumey','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>3,'DistrictName'=>'Lohit','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>3,'DistrictName'=>'Lower Dibang Valley','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>3,'DistrictName'=>'Lower Subansiri','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>3,'DistrictName'=>'Papum Pare','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>3,'DistrictName'=>'Tawang','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>3,'DistrictName'=>'Tirap','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>3,'DistrictName'=>'Dibang Valley','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>3,'DistrictName'=>'Upper Siang','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>3,'DistrictName'=>'Upper Subansiri','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>3,'DistrictName'=>'West Kameng','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>3,'DistrictName'=>'West Siang','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>4,'DistrictName'=>'Baksa','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>4,'DistrictName'=>'Barpeta','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>4,'DistrictName'=>'Bongaigao','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>4,'DistrictName'=>'Cachar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>4,'DistrictName'=>'Chirang','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>4,'DistrictName'=>'Darrang','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>4,'DistrictName'=>'Dhemaji','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>4,'DistrictName'=>'Dima Hasao','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>4,'DistrictName'=>'Dhubri','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>4,'DistrictName'=>'Dibrugarh','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>4,'DistrictName'=>'Goalpara','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>4,'DistrictName'=>'Golaghat','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>4,'DistrictName'=>'Hailakandi','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>4,'DistrictName'=>'Jorhat','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>4,'DistrictName'=>'Kamrup','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>4,'DistrictName'=>'Kamrup Metropolita','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>4,'DistrictName'=>'Karbi Anglong','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>4,'DistrictName'=>'Karimganj','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>4,'DistrictName'=>'Kokrajhar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>4,'DistrictName'=>'Lakhimpur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>4,'DistrictName'=>'Morigao','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>4,'DistrictName'=>'Nagao','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>4,'DistrictName'=>'Nalbari','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>4,'DistrictName'=>'Sivasagar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>4,'DistrictName'=>'Sonitpur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>4,'DistrictName'=>'Tinsukia','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>4,'DistrictName'=>'Udalguri','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>5,'DistrictName'=>'Araria','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>5,'DistrictName'=>'Arwal','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>5,'DistrictName'=>'Aurangabad','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>5,'DistrictName'=>'Banka','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>5,'DistrictName'=>'Begusarai','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>5,'DistrictName'=>'Bhagalpur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>5,'DistrictName'=>'Bhojpur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>5,'DistrictName'=>'Buxar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>5,'DistrictName'=>'Darbhanga','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>5,'DistrictName'=>'East Champara','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>5,'DistrictName'=>'Gaya','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>5,'DistrictName'=>'Gopalganj','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>5,'DistrictName'=>'Jamui','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>5,'DistrictName'=>'Jehanabad','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>5,'DistrictName'=>'Kaimur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>5,'DistrictName'=>'Katihar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>5,'DistrictName'=>'Khagaria','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>5,'DistrictName'=>'Kishanganj','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>5,'DistrictName'=>'Lakhisarai','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>5,'DistrictName'=>'Madhepura','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>5,'DistrictName'=>'Madhubani','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>5,'DistrictName'=>'Munger','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>5,'DistrictName'=>'Muzaffarpur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>5,'DistrictName'=>'Nalanda','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>5,'DistrictName'=>'Nawada','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>5,'DistrictName'=>'Patna','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>5,'DistrictName'=>'Purnia','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>5,'DistrictName'=>'Rohtas','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>5,'DistrictName'=>'Saharsa','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>5,'DistrictName'=>'Samastipur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>5,'DistrictName'=>'Sara','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>5,'DistrictName'=>'Sheikhpura','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>5,'DistrictName'=>'Sheohar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>5,'DistrictName'=>'Sitamarhi','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>5,'DistrictName'=>'Siwa','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>5,'DistrictName'=>'Supaul','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>5,'DistrictName'=>'Vaishali','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>5,'DistrictName'=>'West Champara','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>6,'DistrictName'=>'Chandigarh','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>7,'DistrictName'=>'Bastar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>7,'DistrictName'=>'Bijapur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>7,'DistrictName'=>'Bilaspur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>7,'DistrictName'=>'Dantewada','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>7,'DistrictName'=>'Dhamtari','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>7,'DistrictName'=>'Durg','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>7,'DistrictName'=>'Jashpur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>7,'DistrictName'=>'Janjgir-Champa','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>7,'DistrictName'=>'Korba','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>7,'DistrictName'=>'Koriya','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>7,'DistrictName'=>'Kanker','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>7,'DistrictName'=>'Kabirdham (formerly Kawardha);','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>7,'DistrictName'=>'Mahasamund','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>7,'DistrictName'=>'Narayanpur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>7,'DistrictName'=>'Raigarh','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>7,'DistrictName'=>'Rajnandgao','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>7,'DistrictName'=>'Raipur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>7,'DistrictName'=>'Surajpur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>8,'DistrictName'=>'Dadra and Nagar Haveli','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>9,'DistrictName'=>'Dama','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>9,'DistrictName'=>'Diu','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>10,'DistrictName'=>'Central Delhi','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>10,'DistrictName'=>'East Delhi','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>10,'DistrictName'=>'New Delhi','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>10,'DistrictName'=>'North Delhi','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>10,'DistrictName'=>'North East Delhi','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>10,'DistrictName'=>'North West Delhi','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>10,'DistrictName'=>'South Delhi','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>10,'DistrictName'=>'South West Delhi','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>10,'DistrictName'=>'West Delhi','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>11,'DistrictName'=>'North Goa','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>11,'DistrictName'=>'South Goa','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>12,'DistrictName'=>'Ahmedabad','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>12,'DistrictName'=>'Amreli','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>12,'DistrictName'=>'Anand','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>12,'DistrictName'=>'Aravalli','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>12,'DistrictName'=>'Banaskantha','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>12,'DistrictName'=>'Bharuch','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>12,'DistrictName'=>'Bhavnagar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>12,'DistrictName'=>'Dahod','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>12,'DistrictName'=>'Dang','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>12,'DistrictName'=>'Gandhinagar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>12,'DistrictName'=>'Jamnagar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>12,'DistrictName'=>'Junagadh','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>12,'DistrictName'=>'Kutch','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>12,'DistrictName'=>'Kheda','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>12,'DistrictName'=>'Mehsana','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>12,'DistrictName'=>'Narmada','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>12,'DistrictName'=>'Navsari','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>12,'DistrictName'=>'Pata','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>12,'DistrictName'=>'Panchmahal','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>12,'DistrictName'=>'Porbandar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>12,'DistrictName'=>'Rajkot','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>12,'DistrictName'=>'Sabarkantha','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>12,'DistrictName'=>'Surendranagar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>12,'DistrictName'=>'Surat','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>12,'DistrictName'=>'Tapi','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>12,'DistrictName'=>'Vadodara','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>12,'DistrictName'=>'Valsad','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>13,'DistrictName'=>'Ambala','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>13,'DistrictName'=>'Bhiwani','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>13,'DistrictName'=>'Faridabad','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>13,'DistrictName'=>'Fatehabad','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>13,'DistrictName'=>'Gurgao','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>13,'DistrictName'=>'Hissar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>13,'DistrictName'=>'Jhajjar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>13,'DistrictName'=>'Jind','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>13,'DistrictName'=>'Karnal','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>13,'DistrictName'=>'Kaithal','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>13,'DistrictName'=>'Kurukshetra','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>13,'DistrictName'=>'Mahendragarh','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>13,'DistrictName'=>'Mewat','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>13,'DistrictName'=>'Palwal','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>13,'DistrictName'=>'Panchkula','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>13,'DistrictName'=>'Panipat','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>13,'DistrictName'=>'Rewari','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>13,'DistrictName'=>'Rohtak','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>13,'DistrictName'=>'Sirsa','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>13,'DistrictName'=>'Sonipat','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>13,'DistrictName'=>'Yamuna Nagar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>14,'DistrictName'=>'Bilaspur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>14,'DistrictName'=>'Chamba','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>14,'DistrictName'=>'Hamirpur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>14,'DistrictName'=>'Kangra','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>14,'DistrictName'=>'Kinnaur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>14,'DistrictName'=>'Kullu','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>14,'DistrictName'=>'Lahaul and Spiti','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>14,'DistrictName'=>'Mandi','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>14,'DistrictName'=>'Shimla','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>14,'DistrictName'=>'Sirmaur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>14,'DistrictName'=>'Sola','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>14,'DistrictName'=>'Una','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>15,'DistrictName'=>'Anantnag','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>15,'DistrictName'=>'Badgam','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>15,'DistrictName'=>'Bandipora','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>15,'DistrictName'=>'Baramulla','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>15,'DistrictName'=>'Doda','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>15,'DistrictName'=>'Ganderbal','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>15,'DistrictName'=>'Jammu','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>15,'DistrictName'=>'Kargil','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>15,'DistrictName'=>'Kathua','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>15,'DistrictName'=>'Kishtwar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>15,'DistrictName'=>'Kupwara','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>15,'DistrictName'=>'Kulgam','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>15,'DistrictName'=>'Leh','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>15,'DistrictName'=>'Poonch','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>15,'DistrictName'=>'Pulwama','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>15,'DistrictName'=>'Rajouri','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>15,'DistrictName'=>'Ramba','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>15,'DistrictName'=>'Reasi','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>15,'DistrictName'=>'Samba','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>15,'DistrictName'=>'Shopia','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>15,'DistrictName'=>'Srinagar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>15,'DistrictName'=>'Udhampur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>16,'DistrictName'=>'Bokaro','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>16,'DistrictName'=>'Chatra','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>16,'DistrictName'=>'Deoghar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>16,'DistrictName'=>'Dhanbad','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>16,'DistrictName'=>'Dumka','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>16,'DistrictName'=>'East Singhbhum','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>16,'DistrictName'=>'Garhwa','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>16,'DistrictName'=>'Giridih','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>16,'DistrictName'=>'Godda','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>16,'DistrictName'=>'Gumla','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>16,'DistrictName'=>'Hazaribag','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>16,'DistrictName'=>'Jamtara','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>16,'DistrictName'=>'Khunti','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>16,'DistrictName'=>'Koderma','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>16,'DistrictName'=>'Latehar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>16,'DistrictName'=>'Lohardaga','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>16,'DistrictName'=>'Pakur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>16,'DistrictName'=>'Palamu','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>16,'DistrictName'=>'Ramgarh','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>16,'DistrictName'=>'Ranchi','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>16,'DistrictName'=>'Sahibganj','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>16,'DistrictName'=>'Seraikela Kharsawa','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>16,'DistrictName'=>'Simdega','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>16,'DistrictName'=>'West Singhbhum','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>17,'DistrictName'=>'Bagalkot','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>17,'DistrictName'=>'Bangalore Rural','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>17,'DistrictName'=>'Bangalore Urba','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>17,'DistrictName'=>'Belgaum','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>17,'DistrictName'=>'Bellary','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>17,'DistrictName'=>'Bidar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>17,'DistrictName'=>'Bijapur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>17,'DistrictName'=>'Chamarajnagar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>17,'DistrictName'=>'Chikkamagaluru','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>17,'DistrictName'=>'Chikkaballapur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>17,'DistrictName'=>'Chitradurga','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>17,'DistrictName'=>'Davanagere','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>17,'DistrictName'=>'Dharwad','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>17,'DistrictName'=>'Dakshina Kannada','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>17,'DistrictName'=>'Gadag','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>17,'DistrictName'=>'Gulbarga','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>17,'DistrictName'=>'Hassa','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>17,'DistrictName'=>'Haveri','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>17,'DistrictName'=>'Kodagu','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>17,'DistrictName'=>'Kolar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>17,'DistrictName'=>'Koppal','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>17,'DistrictName'=>'Mandya','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>17,'DistrictName'=>'Mysore','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>17,'DistrictName'=>'Raichur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>17,'DistrictName'=>'Shimoga','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>17,'DistrictName'=>'Tumkur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>17,'DistrictName'=>'Udupi','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>17,'DistrictName'=>'Uttara Kannada','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>17,'DistrictName'=>'Ramanagara','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>17,'DistrictName'=>'Yadgir','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>18,'DistrictName'=>'Alappuzha','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>18,'DistrictName'=>'Ernakulam','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>18,'DistrictName'=>'Idukki','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>18,'DistrictName'=>'Kannur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>18,'DistrictName'=>'Kasaragod','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>18,'DistrictName'=>'Kollam','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>18,'DistrictName'=>'Kottayam','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>18,'DistrictName'=>'Kozhikode','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>18,'DistrictName'=>'Malappuram','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>18,'DistrictName'=>'Palakkad','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>18,'DistrictName'=>'Pathanamthitta','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>18,'DistrictName'=>'Thrissur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>18,'DistrictName'=>'Thiruvananthapuram','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>18,'DistrictName'=>'Wayanad','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>19,'DistrictName'=>'Lakshadweep','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Agar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Alirajpur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Anuppur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Ashok Nagar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Balaghat','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Barwani','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Betul','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Bhind','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Bhopal','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Burhanpur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Chhatarpur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Chhindwara','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Damoh','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Datia','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Dewas','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Dhar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Dindori','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Guna','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Gwalior','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Harda','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Hoshangabad','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Indore','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Jabalpur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Jhabua','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Katni','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Khandwa (East Nimar);','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Khargone (West Nimar);','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Mandla','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Mandsaur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Morena','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Narsinghpur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Neemuch','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Panna','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Raise','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Rajgarh','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Ratlam','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Rewa','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Sagar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Satna','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Sehore','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Seoni','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Shahdol','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Shajapur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Sheopur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Shivpuri','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Sidhi','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Singrauli','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Tikamgarh','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Ujjai','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Umaria','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>20,'DistrictName'=>'Vidisha','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>21,'DistrictName'=>'Ahmednagar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>21,'DistrictName'=>'Akola','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>21,'DistrictName'=>'Amravati','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>21,'DistrictName'=>'Aurangabad','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>21,'DistrictName'=>'Beed','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>21,'DistrictName'=>'Bhandara','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>21,'DistrictName'=>'Buldhana','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>21,'DistrictName'=>'Chandrapur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>21,'DistrictName'=>'Dhule','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>21,'DistrictName'=>'Gadchiroli','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>21,'DistrictName'=>'Gondia','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>21,'DistrictName'=>'Hingoli','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>21,'DistrictName'=>'Jalgao','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>21,'DistrictName'=>'Jalna','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>21,'DistrictName'=>'Kolhapur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>21,'DistrictName'=>'Latur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>21,'DistrictName'=>'Mumbai City','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>21,'DistrictName'=>'Mumbai suburba','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>21,'DistrictName'=>'Nanded','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>21,'DistrictName'=>'Nandurbar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>21,'DistrictName'=>'Nagpur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>21,'DistrictName'=>'Nashik','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>21,'DistrictName'=>'Osmanabad','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>21,'DistrictName'=>'Parbhani','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>21,'DistrictName'=>'Pune','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>21,'DistrictName'=>'Raigad','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>21,'DistrictName'=>'Ratnagiri','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>21,'DistrictName'=>'Sangli','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>21,'DistrictName'=>'Satara','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>21,'DistrictName'=>'Sindhudurg','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>21,'DistrictName'=>'Solapur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>21,'DistrictName'=>'Thane','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>21,'DistrictName'=>'Wardha','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>21,'DistrictName'=>'Washim','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>21,'DistrictName'=>'Yavatmal','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>22,'DistrictName'=>'Bishnupur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>22,'DistrictName'=>'Churachandpur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>22,'DistrictName'=>'Chandel','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>22,'DistrictName'=>'Imphal East','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>22,'DistrictName'=>'Senapati','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>22,'DistrictName'=>'Tamenglong','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>22,'DistrictName'=>'Thoubal','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>22,'DistrictName'=>'Ukhrul','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>22,'DistrictName'=>'Imphal West','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>23,'DistrictName'=>'East Garo Hills','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>23,'DistrictName'=>'East Khasi Hills','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>23,'DistrictName'=>'Jaintia Hills','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>23,'DistrictName'=>'Ri Bhoi','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>23,'DistrictName'=>'South Garo Hills','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>23,'DistrictName'=>'West Garo Hills','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>23,'DistrictName'=>'West Khasi Hills','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>24,'DistrictName'=>'Aizawl','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>24,'DistrictName'=>'Champhai','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>24,'DistrictName'=>'Kolasib','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>24,'DistrictName'=>'Lawngtlai','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>24,'DistrictName'=>'Lunglei','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>24,'DistrictName'=>'Mamit','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>24,'DistrictName'=>'Saiha','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>24,'DistrictName'=>'Serchhip','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>25,'DistrictName'=>'Dimapur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>25,'DistrictName'=>'Kiphire','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>25,'DistrictName'=>'Kohima','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>25,'DistrictName'=>'Longleng','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>25,'DistrictName'=>'Mokokchung','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>25,'DistrictName'=>'Mo','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>25,'DistrictName'=>'Pere','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>25,'DistrictName'=>'Phek','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>25,'DistrictName'=>'Tuensang','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>25,'DistrictName'=>'Wokha','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>25,'DistrictName'=>'Zunheboto','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>26,'DistrictName'=>'Angul','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>26,'DistrictName'=>'Boudh (Bauda);','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>26,'DistrictName'=>'Bhadrak','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>26,'DistrictName'=>'Balangir','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>26,'DistrictName'=>'Bargarh (Baragarh);','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>26,'DistrictName'=>'Balasore','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>26,'DistrictName'=>'Cuttack','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>26,'DistrictName'=>'Debagarh (Deogarh);','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>26,'DistrictName'=>'Dhenkanal','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>26,'DistrictName'=>'Ganjam','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>26,'DistrictName'=>'Gajapati','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>26,'DistrictName'=>'Jharsuguda','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>26,'DistrictName'=>'Jajpur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>26,'DistrictName'=>'Jagatsinghpur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>26,'DistrictName'=>'Khordha','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>26,'DistrictName'=>'Kendujhar (Keonjhar);','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>26,'DistrictName'=>'Kalahandi','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>26,'DistrictName'=>'Kandhamal','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>26,'DistrictName'=>'Koraput','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>26,'DistrictName'=>'Kendrapara','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>26,'DistrictName'=>'Malkangiri','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>26,'DistrictName'=>'Mayurbhanj','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>26,'DistrictName'=>'Nabarangpur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>26,'DistrictName'=>'Nuapada','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>26,'DistrictName'=>'Nayagarh','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>26,'DistrictName'=>'Puri','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>26,'DistrictName'=>'Rayagada','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>26,'DistrictName'=>'Sambalpur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>26,'DistrictName'=>'Subarnapur (Sonepur);','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>26,'DistrictName'=>'Sundergarh','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>27,'DistrictName'=>'Karaikal','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>27,'DistrictName'=>'Mahe','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>27,'DistrictName'=>'Pondicherry','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>27,'DistrictName'=>'Yanam','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>28,'DistrictName'=>'Amritsar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>28,'DistrictName'=>'Barnala','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>28,'DistrictName'=>'Bathinda','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>28,'DistrictName'=>'Firozpur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>28,'DistrictName'=>'Faridkot','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>28,'DistrictName'=>'Fatehgarh Sahib','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>28,'DistrictName'=>'Fazilka','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>28,'DistrictName'=>'Gurdaspur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>28,'DistrictName'=>'Hoshiarpur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>28,'DistrictName'=>'Jalandhar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>28,'DistrictName'=>'Kapurthala','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>28,'DistrictName'=>'Ludhiana','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>28,'DistrictName'=>'Mansa','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>28,'DistrictName'=>'Moga','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>28,'DistrictName'=>'Sri Muktsar Sahib','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>28,'DistrictName'=>'Pathankot','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>28,'DistrictName'=>'Patiala','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>28,'DistrictName'=>'Rupnagar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>28,'DistrictName'=>'Ajitgarh (Mohali);','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>28,'DistrictName'=>'Sangrur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>28,'DistrictName'=>'Shahid Bhagat Singh Nagar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>28,'DistrictName'=>'Tarn Tara','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>29,'DistrictName'=>'Ajmer','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>29,'DistrictName'=>'Alwar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>29,'DistrictName'=>'Bikaner','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>29,'DistrictName'=>'Barmer','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>29,'DistrictName'=>'Banswara','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>29,'DistrictName'=>'Bharatpur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>29,'DistrictName'=>'Bara','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>29,'DistrictName'=>'Bundi','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>29,'DistrictName'=>'Bhilwara','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>29,'DistrictName'=>'Churu','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>29,'DistrictName'=>'Chittorgarh','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>29,'DistrictName'=>'Dausa','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>29,'DistrictName'=>'Dholpur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>29,'DistrictName'=>'Dungapur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>29,'DistrictName'=>'Ganganagar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>29,'DistrictName'=>'Hanumangarh','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>29,'DistrictName'=>'Jhunjhunu','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>29,'DistrictName'=>'Jalore','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>29,'DistrictName'=>'Jodhpur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>29,'DistrictName'=>'Jaipur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>29,'DistrictName'=>'Jaisalmer','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>29,'DistrictName'=>'Jhalawar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>29,'DistrictName'=>'Karauli','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>29,'DistrictName'=>'Kota','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>29,'DistrictName'=>'Nagaur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>29,'DistrictName'=>'Pali','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>29,'DistrictName'=>'Pratapgarh','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>29,'DistrictName'=>'Rajsamand','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>29,'DistrictName'=>'Sikar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>29,'DistrictName'=>'Sawai Madhopur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>29,'DistrictName'=>'Sirohi','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>29,'DistrictName'=>'Tonk','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>29,'DistrictName'=>'Udaipur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>30,'DistrictName'=>'East Sikkim','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>30,'DistrictName'=>'North Sikkim','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>30,'DistrictName'=>'South Sikkim','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>30,'DistrictName'=>'West Sikkim','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>31,'DistrictName'=>'Ariyalur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>31,'DistrictName'=>'Chennai','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>31,'DistrictName'=>'Coimbatore','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>31,'DistrictName'=>'Cuddalore','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>31,'DistrictName'=>'Dharmapuri','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>31,'DistrictName'=>'Dindigul','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>31,'DistrictName'=>'Erode','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>31,'DistrictName'=>'kallakurichi','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>31,'DistrictName'=>'Kanchipuram','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>31,'DistrictName'=>'Kanyakumari','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>31,'DistrictName'=>'Karur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>31,'DistrictName'=>'Krishnagiri','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>31,'DistrictName'=>'Madurai','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>31,'DistrictName'=>'Nagapattinam','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>31,'DistrictName'=>'Nilgiris','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>31,'DistrictName'=>'Namakkal','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>31,'DistrictName'=>'Perambalur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>31,'DistrictName'=>'Pudukkottai','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>31,'DistrictName'=>'Ramanathapuram','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>31,'DistrictName'=>'Salem','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>31,'DistrictName'=>'Sivaganga','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>31,'DistrictName'=>'Tirupur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>31,'DistrictName'=>'Tiruchirappalli','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>31,'DistrictName'=>'Theni','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>31,'DistrictName'=>'Tirunelveli','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>31,'DistrictName'=>'Thanjavur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>31,'DistrictName'=>'Thoothukudi','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>31,'DistrictName'=>'Tiruvallur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>31,'DistrictName'=>'Tiruvarur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>31,'DistrictName'=>'Tiruvannamalai','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>31,'DistrictName'=>'Vellore','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>31,'DistrictName'=>'Viluppuram','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>31,'DistrictName'=>'Virudhunagar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>32,'DistrictName'=>'Adilabad','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>32,'DistrictName'=>'Hyderabad','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>32,'DistrictName'=>'Karimnagar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>32,'DistrictName'=>'Khammam','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>32,'DistrictName'=>'Mahbubnagar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>32,'DistrictName'=>'Medak','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>32,'DistrictName'=>'Nalgonda','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>32,'DistrictName'=>'Nizamabad','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>32,'DistrictName'=>'Ranga Reddy','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>32,'DistrictName'=>'Warangal','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>33,'DistrictName'=>'Dhalai','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>33,'DistrictName'=>'North Tripura','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>33,'DistrictName'=>'South Tripura','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>33,'DistrictName'=>'Khowai','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>33,'DistrictName'=>'West Tripura','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Agra','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Aligarh','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Allahabad','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Ambedkar Nagar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Auraiya','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Azamgarh','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Bagpat','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Bahraich','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Ballia','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Balrampur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Banda','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Barabanki','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Bareilly','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Basti','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Bijnor','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Budau','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Bulandshahr','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Chandauli','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Amethi (Chhatrapati Shahuji Maharaj Nagar)','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Chitrakoot','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Deoria','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Etah','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Etawah','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Faizabad','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Farrukhabad','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Fatehpur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Firozabad','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Gautam Buddh Nagar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Ghaziabad','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Ghazipur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Gonda','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Gorakhpur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Hamirpur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Hardoi','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Hathras (Mahamaya Nagar);','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Jalau','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Jaunpur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Jhansi','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Jyotiba Phule Nagar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Kannauj','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Kanpur Dehat (Ramabai Nagar);','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Kanpur Nagar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Kanshi Ram Nagar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Kaushambi','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Kushinagar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Lakhimpur Kheri','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Lalitpur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Lucknow','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Maharajganj','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Mahoba','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Mainpuri','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Mathura','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Mau','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Meerut','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Mirzapur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Moradabad','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Muzaffarnagar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Panchsheel Nagar (Hapur);','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Pilibhit','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Pratapgarh','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Raebareli','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Rampur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Saharanpur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Sambhal(Bheem Nagar);','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Sant Kabir Nagar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Sant Ravidas Nagar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Shahjahanpur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Shamli','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Shravasti','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Siddharthnagar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Sitapur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Sonbhadra','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Sultanpur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Unnao','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>35,'DistrictName'=>'Varanasi','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>34,'DistrictName'=>'Almora','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>34,'DistrictName'=>'Bageshwar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>34,'DistrictName'=>'Chamoli','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>34,'DistrictName'=>'Champawat','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>34,'DistrictName'=>'Dehradu','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>34,'DistrictName'=>'Haridwar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>34,'DistrictName'=>'Nainital','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>34,'DistrictName'=>'Pauri Garhwal','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>34,'DistrictName'=>'Pithoragarh','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>34,'DistrictName'=>'Rudraprayag','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>34,'DistrictName'=>'Tehri Garhwal','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>34,'DistrictName'=>'Udham Singh Nagar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>34,'DistrictName'=>'Uttarkashi','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>36,'DistrictName'=>'Bankura','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>36,'DistrictName'=>'Bardhama','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>36,'DistrictName'=>'Birbhum','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>36,'DistrictName'=>'Cooch Behar','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>36,'DistrictName'=>'Dakshin Dinajpur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>36,'DistrictName'=>'Darjeeling','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>36,'DistrictName'=>'Hooghly','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>36,'DistrictName'=>'Howrah','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>36,'DistrictName'=>'Jalpaiguri','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>36,'DistrictName'=>'Kolkata','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>36,'DistrictName'=>'Maldah','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>36,'DistrictName'=>'Murshidabad','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>36,'DistrictName'=>'Nadia','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>36,'DistrictName'=>'North 24 Parganas','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>36,'DistrictName'=>'Paschim Medinipur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>36,'DistrictName'=>'Purba Medinipur','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>36,'DistrictName'=>'Purulia','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>36,'DistrictName'=>'South 24 Parganas','created_at'=>now(),'updated_at'=>now()],
            ['state_id'=>36,'DistrictName'=>'Uttar Dinajpur','created_at'=>now(),'updated_at'=>now()]];

        DB::table('districts')->insert($District);
        
        DB::table('admins')->insert([
            'name' => 'Admin',
            'email' => 'admin@admin.com',
            'password' => bcrypt('123456'),
        ]);
    }
}
